name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: npm install
        run: npm install

      - name: Upload static files to Blob Storage
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az storage blob upload-batch --account-name photonoteshusic --account-key "${{ secrets.AZURE_STORAGE_KEY }}" --destination static/static --source ./public --overwrite true

      - name: Zip artifact
        run: zip -r deploy.zip . -x '.git/*'

      - name: Deploy to Azure Web App
        run: |
          curl -X POST \
            -u "${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_PASS }}" \
            --data-binary @deploy.zip \
            -H "Content-Type: application/octet-stream" \
            "https://photo-notes-husic.scm.azurewebsites.net/api/zipdeploy?isAsync=true"
